### ISSUE TITLE
Trello support not working

### ISSUE THREAD

**Issue by szoper** [qoomon/Jira-Issue-Card-Printer#56]
I've tried both solutions for read-only and read-and-write Trello boards but they both result in this error message:

```
ERROR {"stack":"TypeError: Cannot read property 'match' of undefined
    at HTMLSpanElement.<anonymous> (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:4:4800)
    at https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:1:13622
    at Function.map (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:1:15865)
    at he.fn.init.map (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:1:13590)
    at Object.o [as getSelectedIssueKeyList] (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:4:4758)
    at https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:5:4261
    at Object.r.13../lib/bitbucket-issue-tracker (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:5:4717)
    at i (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:1:254)
    at e (https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:1:420)
    at https://qoomon.github.io/Jira-Issue-Card-Printer/bookmarklet.js:1:437","message":"Cannot read property 'match' of undefined"}
```

**Comment by qoomon** [comment]
I'll have look one moment.

**Comment by qoomon** [comment]
Should not throw the error anymore, unfortunately column selection only works in read only mode. I didn't figured out how to select a column with read write access
